### ISSUE TITLE
sea-query 1.0.0-rc.23 fails to compile on Rust 1.92 - VALUE_SIZE exceeds 32 bytes

### ISSUE THREAD

**Issue by UMCEKO** [SeaQL/sea-query#1030]
## Description

`sea-query 1.0.0-rc.23` fails to compile on Rust 1.92.0 with a compile-time panic about VALUE_SIZE exceeding 32 bytes. This happens even with minimal features enabled (just `sqlx-postgres`).

## Steps to Reproduce

1. Use Rust 1.92.0
2. Add `sea-orm = "2.0.0-rc.22"` (or any version that pulls in `sea-query 1.0.0-rc.23`)
3. Run `cargo build`

### Expected Behavior

The crate should compile successfully.

### Actual Behavior

```
error[E0080]: evaluation panicked: the size of Value shouldn't be greater than the expected MAX_VALUE_SIZE (32 bytes by default)
   --> /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sea-query-1.0.0-rc.23/src/value.rs:382:31
    |
382 | pub const VALUE_SIZE: usize = check_value_size();
    |                               ^^^^^^^^^^^^^^^^^^ evaluation of \`value::VALUE_SIZE\` failed inside this call
    |
note: inside \`check_value_size\`
   --> /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sea-query-1.0.0-rc.23/src/value.rs:419:9
    |
419 | /         panic\!(
420 | |             "the size of Value shouldn't be greater than the expected MAX_VALUE_SIZE (32 bytes by default)"
421 | |         )
    | |_________^ the failure occurred here
```

### Reproduces How Often

Always on Rust 1.92.0

## Versions

- Rust: `rustc 1.92.0 (ded5c06cf 2025-12-08)`
- sea-query: 1.0.0-rc.23
- sea-orm: 2.0.0-rc.22 (pulls in sea-query 1.0.0-rc.23)
- OS: Linux 6.18.1-arch1-2

## Additional Information

This appears to be related to changes in Rust 1.92's const evaluation or type sizes. The same code compiles fine with `sea-query 1.0.0-rc.17` (used by `sea-orm 2.0.0-rc.18`).

The workaround is to use `sea-orm 2.0.0-rc.18` which depends on `sea-query 1.0.0-rc.17`.

Related: #971, #972 (similar VALUE_SIZE issues with serde_json preserve_order)

**Comment by UMCEKO** [comment]
Additional findings:

- `sea-orm 2.0.0-rc.22` requires **exactly** `sea-query = "=1.0.0-rc.23"` - they're locked together
- Cannot downgrade sea-query independently while using sea-orm rc.19+
- `sea-orm 2.0.0-rc.18` works because it uses `sea-query 1.0.0-rc.17`

The issue started somewhere between sea-query rc.17 and rc.23.
