### ISSUE TITLE
sea-query-rusqlite 0.1.0 doesn't compile with sea-query 0.28.0

### ISSUE THREAD

**Issue by evgeniy-terekhin** [SeaQL/sea-query#553]
MRE:

```
use sea_query::{Query, SqliteQueryBuilder};
use sea_query_rusqlite::RusqliteBinder;

fn main() {
    let (sql, values) = Query::select().build_rusqlite(SqliteQueryBuilder);
}
```

with these deps it compiles
```
[dependencies]
sea-query = "0.27"
sea-query-rusqlite = "0.1"
```

with these it doesn't
```
[dependencies]
sea-query = "0.28"
sea-query-rusqlite = "0.1"
```

error message
```
error[E0599]: no method named `build_rusqlite` found for struct `sea_query::SelectStatement` in the current scope
 --> src/main.rs:5:41
  |
5 |     let (sql, values) = Query::select().build_rusqlite(SqliteQueryBuilder);
  |                                         ^^^^^^^^^^^^^^ method not found in `sea_query::SelectStatement`

warning: unused import: `sea_query_rusqlite::RusqliteBinder`
 --> src/main.rs:2:5
  |
2 | use sea_query_rusqlite::RusqliteBinder;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default
  ```

**Comment by evgeniy-terekhin** [comment]
@ikrivosheev could you please take a look?

**Comment by ikrivosheev** [comment]
@evgeniy-terekhin, hello! Thank you for the  report! 

@tyt2y3, can you publish new version `sea-query-rusqlite`?

**Comment by billy1624** [comment]
Alright, let me check. Give me a second

**Comment by billy1624** [comment]
Hey @evgeniy-terekhin, I just released `sea-query-rusqlite` 0.2 which depends on `sea-query` 0.28
https://crates.io/crates/sea-query-rusqlite/0.2.0

**Comment by billy1624** [comment]
I think it'd be easier to manage sea-query crates if all of their version number is in sync. E.g.
- `sea-query-rusqlite` 0.28 should be used together with `sea-query` 0.28
- `sea-query-binder` 0.28 should be used together with `sea-query` 0.28
- `sea-query-derive` 0.28 should be used together with `sea-query` 0.28

Also, we better have a script to bump the version across all crates
https://github.com/SeaQL/sea-orm/blob/master/build-tools/bump-version.sh

**Comment by ikrivosheev** [comment]
@billy1624 hello! I don't see changes: https://github.com/SeaQL/sea-query/blob/0.28.x/sea-query-rusqlite/Cargo.toml

**Comment by billy1624** [comment]
Updated. https://github.com/SeaQL/sea-query/commit/450c973b9f1d6a53000d1badf4f1639e5bcae598

**Comment by billy1624** [comment]
Thanks for the reminder hahaa

**Comment by evgeniy-terekhin** [comment]
> Hey @evgeniy-terekhin, I just released `sea-query-rusqlite` 0.2 which depends on `sea-query` 0.28 https://crates.io/crates/sea-query-rusqlite/0.2.0

thanks! I can confirm that it fixed my problem

**Comment by ikrivosheev** [comment]
Thanks everyone!
